service: yt-playlist-dl-helpers

frameworkVersion: ">=1.1.0"

custom:
  bucket: yt-playlist

provider:
  name: aws
  ecr:
    images:
      yt-playlist-dl:
        path: ./
  stage: dev
  region: eu-central-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:PutObjectTagging
            - s3:PutObjectAcl
          Resource: "arn:aws:s3:::${self:custom.bucket}/*"
  stackTags:
    GIT_COMMIT: ${git:sha1}

functions:
  resolve:
    image:
      name: yt-playlist-dl
      command:
        - handler.resolve
    memorySize: 1536
    timeout: 180
    environment:
      BUCKET: ${self:custom.bucket}
  convert:
    image:
      name: yt-playlist-dl
      command:
        - handler.convert
    memorySize: 1536
    timeout: 120
    environment:
      BUCKET: ${self:custom.bucket}

plugins:
  - serverless-plugin-git-variables
