# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

executors:
  default_executor:
    docker:
      - image: circleci/node:8.17
    working_directory: ~/repo

  lambda_executor:
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: true
    working_directory: ~/repo/lambda_functions

jobs:
  test_and_deploy:
    executor: default_executor
    steps:
      - checkout
      # Update npm to newest version
      - run: sudo npm install -g npm@latest-6
      - run: npm ci

      - run: echo "No tests yet"

      - add_ssh_keys:
          fingerprints:
            - "c7:64:14:51:f8:85:7a:2c:37:64:a2:8e:6b:44:42:c4"
      - run: ssh-keyscan -H $PRODUCTION_SERVER_HOST >> ~/.ssh/known_hosts
      - run: npx shipit production deploy

  deploy_lambda:
    executor: lambda_executor
    steps:
      - checkout:
          path: ~/repo
      - run: npm -g install serverless serverless-plugin-git-variables
      - run: npx sls deploy

workflows:
  version: 2

  test_and_deploy:
    jobs:
      - test_and_deploy:
          filters:
            branches:
              only:
                - master
      - deploy_lambda:
          filters:
            branches:
              only:
                - master

  scheduled_lambda_deploy:
    jobs:
      - deploy_lambda
    triggers:
      - schedule:
          cron: "0 0 * * 0" # At 00:00 on Sunday
          filters:
            branches:
              only:
                - master

