# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

      # Update npm to newest version
      - run: sudo npm install -g npm
      - run: npm ci

      # run tests!
      - run: echo "No tests yet"

      # Deploy lambda functions with the newest youtube-dl version
      - run:
          command: |
            cd lambda_functions
            npm ci
            ./bin/youtube-dl -U
            npx sls deploy

      - run: ssh-keyscan 35.157.234.157 >> ~/.ssh/known_hosts
      - run: npx shipit production deploy
